version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: blog-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blogdb
      - JWT_SECRET=secret
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: blog-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo-data:
